# Project Information
site_name: bjtuse-wiki

# Repository
repo_name: 'AzurIce/bjtuse-wiki'
repo_url: 'https://github.com/AzurIce/bjtuse-wiki'
edit_uri: edit/main/docs/

nav:
  - 简介: # intro
    - 简介: index.md
    # - 如何参与: intro/how-to-contribute.md
    # - 贡献规范: intro/contribute-format.md
    - F.A.Q: intro/faq.md

# Theme
theme:
  language: zh
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.share
    - content.action.edit # 页面右上角的编辑按钮，跳转 GitHub
    - content.action.view
    - content.code.copy
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_javascript:
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  - js/diagram.js

extra_css:
  - css/diagram.css

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  # Images https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.critic # critic markup
  - pymdownx.caret # ^^insert^^ ^superscript^
  - pymdownx.mark  # ==mark==
  - pymdownx.tilde # ~~delete~~ ~subscript~
  - pymdownx.keys  # ++key++
  - admonition
  - pymdownx.details # collapsible admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: table
      anchor_linenums: true
  - pymdownx.blocks.tab:
      alternate_style: true
  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - glightbox # image zoom (mkdocs-glightbox)
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-dates
  - git-revision-date-localized: # (mkdocs-git-revision-date-localized-plugin)
      type: iso_datetime
      enable_creation_date: true
      fallback_to_build_date: true
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors
  - git-committers: # (mkdocs-git-committers-plugin-2)
      repository: AzurIce/bjtuse-wiki
      branch: main