name: 页面无关 Bug 汇报
about: 指出出现的问题
title: '[BUG] '
labels: ["Other Bug / 页面无关的 Bug"]

body:
- type: markdown
  attributes:
    value: 欢迎参与到 bjtuse-wiki 的贡献！请填写以下内容：
- type: checkboxes
  id: confirm
  attributes:
    label: 请选择：
    options:
    - label: 我正在着手修复这个问题
      required: false
- type: textarea
  id: bug
  attributes:
    labels: 页面存在的问题
    description: 简易添加截图以更加清晰地描述你的问题
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    labels: 问题复现方法
  validations:
    required: false