blank_issues_enabled: true
contact_links:
  - name: 查看我们的 F.A.Q.
    url: https://azurice.github.io/bjtuse-wiki/intro/faq/
    about: 提问之前先阅读一下 F.A.Q. 哦~
  # - name: 加入我们的 QQ 群组
  #   about: 在这里可以提问、获取帮助、讨论与 OI Wiki 有关的话题
  # - name: 加入我们的 Telegram 群组
  #   about: 在这里可以提问、获取帮助、讨论与 OI Wiki 有关的话题