name: 新页面请求
description: 请求增加新页面
title: 'Add '
labels: ["Content Request / 内容请求", "Help Wanted / 需要援助"]

body:
- type: markdown
  attributes:
    value: 欢迎参与到 bjtuse-wiki 的贡献！请填写以下内容：
- type: input
  id: pagename
  attributes:
    label: 页面英文名
    description: 添加新页面请填写
    placeholder: page-name
  validations:
    required: false
- type: textarea
  id: page
  attributes:
    label: 页面大致内容
  validations:
    required: true
- type: textarea
  id: reason
  attributes:
    label: 请求原因
  validations:
    required: false